# Zone Auth Configuration
resource "nios_dns_zone_auth" "zone_auth" {
  fqdn = var.fqdn
  view = var.view
  zone_format = var.zone_format
  comment = var.comment
  disable = var.disable
  locked = var.locked
  ns_group = var.ns_group
  grid_primary = var.grid_primary
  grid_secondaries = var.grid_secondaries
  external_primaries = var.external_primaries
  external_secondaries = var.external_secondaries
#   soa_default_ttl = var.soa_default_ttl
#   soa_expire = var.soa_expire
#   soa_negative_ttl = var.soa_negative_ttl
#   soa_refresh = var.soa_refresh
#   soa_retry = var.soa_retry
#   soa_email = var.soa_email
#   soa_serial_number = var.soa_serial_number
#   set_soa_serial_number = var.set_soa_serial_number
  allow_active_dir = var.allow_active_dir
  allow_fixed_rrset_order = var.allow_fixed_rrset_order
  # REMOVED by user: allow_gss_tsig_for_underscore_zone = var.allow_gss_tsig_for_underscore_zone
  allow_gss_tsig_zone_updates = var.allow_gss_tsig_zone_updates
  allow_query = var.allow_query
  allow_transfer = var.allow_transfer
  allow_update = var.allow_update
  allow_update_forwarding = var.allow_update_forwarding
  copy_xfer_to_notify = var.copy_xfer_to_notify
  create_underscore_zones = var.create_underscore_zones
  ddns_force_creation_timestamp_update = var.ddns_force_creation_timestamp_update
  #ddns_principal_group = var.ddns_principal_group
  ddns_principal_tracking = var.ddns_principal_tracking
  ddns_restrict_patterns = var.ddns_restrict_patterns
  ddns_restrict_patterns_list = var.ddns_restrict_patterns_list
  ddns_restrict_protected = var.ddns_restrict_protected
  ddns_restrict_secure = var.ddns_restrict_secure
  ddns_restrict_static = var.ddns_restrict_static
  disable_forwarding = var.disable_forwarding
  dns_integrity_enable = var.dns_integrity_enable
  dns_integrity_frequency = var.dns_integrity_frequency
  #dns_integrity_member = var.dns_integrity_member
  dns_integrity_verbose_logging = var.dns_integrity_verbose_logging
  dnssec_key_params = var.dnssec_key_params
  effective_check_names_policy = var.effective_check_names_policy
  last_queried_acl = var.last_queried_acl
  member_soa_mnames = var.member_soa_mnames
  ms_ad_integrated = var.ms_ad_integrated
  ms_allow_transfer = var.ms_allow_transfer
  ms_allow_transfer_mode = var.ms_allow_transfer_mode
  ms_dc_ns_record_creation = var.ms_dc_ns_record_creation
  ms_ddns_mode = var.ms_ddns_mode
  ms_primaries = var.ms_primaries
  ms_secondaries = var.ms_secondaries
  ms_sync_disabled = var.ms_sync_disabled
  notify_delay = var.notify_delay
  prefix = var.prefix
  # REMOVED by user: record_name_policy = var.record_name_policy
  remove_subzones = var.remove_subzones
  restart_if_needed = var.restart_if_needed
  scavenging_settings = var.scavenging_settings
  # REMOVED by user: srgs = var.srgs
  update_forwarding = var.update_forwarding
  use_allow_active_dir = var.use_allow_active_dir
  use_allow_query = var.use_allow_query
  use_allow_transfer = var.use_allow_transfer
  use_allow_update = var.use_allow_update
  use_allow_update_forwarding = var.use_allow_update_forwarding
  use_check_names_policy = var.use_check_names_policy
  use_copy_xfer_to_notify = var.use_copy_xfer_to_notify
  use_ddns_force_creation_timestamp_update = var.use_ddns_force_creation_timestamp_update
  use_ddns_patterns_restriction = var.use_ddns_patterns_restriction
  use_ddns_principal_security = var.use_ddns_principal_security
  use_ddns_restrict_protected = var.use_ddns_restrict_protected
  use_ddns_restrict_static = var.use_ddns_restrict_static
  use_dnssec_key_params = var.use_dnssec_key_params
  use_external_primary = var.use_external_primary
  use_grid_zone_timer = var.use_grid_zone_timer
  use_notify_delay = var.use_notify_delay
  use_record_name_policy = var.use_record_name_policy
  use_scavenging_settings = var.use_scavenging_settings
  # REMOVED by user: use_soa_email = var.use_soa_email
  # REMOVED by user: extattrs = var.extattrs
}
