name: Acceptance Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*
    paths-ignore:
    - 'README.md'
    - 'Makefile'
    - 'docs/**'
    - 'examples/**'

jobs:
  acceptance-test:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.2.0
        with:
          go-version: '1.24.4'
      - name: Run tests
        timeout-minutes: 120
        env:
          TF_ACC: "1"
          NIOS_HOST_URL: "https://172.28.82.250" #${{ secrets.NIOS_HOST_URL }}
          NIOS_USERNAME: "admin" #${{ secrets.NIOS_USERNAME }}
          NIOS_PASSWORD: "Infoblox@123" #${{ secrets.NIOS_PASSWORD }}
        run: |
          go test $(go list ./... | grep -v 'vendor') -timeout 120m -v -cover
