name: Custom Build Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  custom-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: '1.25.1'
      - name: Build
        run: go build -v ./... > terraform-provider-nios
      - uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-nios
          path: terraform-provider-nios

